# key,value custom filters
program,REGULATORY_A
network,DMZ
# Exclude any server whose INV_Beneficiary_Account matches one of these values (comma-separated).
FILTER_BENEFICIARY_ACCOUNT_NOT_TAKEN=
FILTER_OWNER_ACCOUNT_NOT_TAKEN=
