import os
from dotenv import load_dotenv

load_dotenv()

ELASTICSEARCH = {
    "HOST": (os.getenv("ELASTICSEARCH_WRITE_HOST") or "").strip().strip("'").strip('"'),
    "PORT": (os.getenv("ELASTICSEARCH_WRITE_PORT") or "").strip().strip("'").strip('"'),
    "USERNAME": (os.getenv("ELASTICSEARCH_WRITE_LOGIN") or "").strip().strip("'").strip('"'),
    "PASSWORD": (os.getenv("ELASTICSEARCH_WRITE_PASS") or "").strip().strip("'").strip('"'),
}

PCE = {
    "BASE_URL": (os.getenv("PCE_L1_FQDN") or "").strip().strip("'").strip('"'),
    "API_KEY": (os.getenv("PCE_API_KEY") or "").strip().strip("'").strip('"'),
    "API_SECRET": (os.getenv("PCE_API_SECRET") or "").strip().strip("'").strip('"'),
    "ORG_ID": (os.getenv("PCE_ORG_ID") or "1").strip().strip("'").strip('"'),
}

DALI = {
    "BASE_URL": (os.getenv("DALI_BASE_URL") or "").strip().strip("'").strip('"'),
    "TOKEN_URL": (os.getenv("SGMARKET_TOKEN_URL") or "").strip().strip("'").strip('"'),
    "CLIENT_ID": (os.getenv("SGCONNECT_CLIENT_ID") or "").strip().strip("'").strip('"'),
    "CLIENT_SECRET": (os.getenv("SGCONNECT_CLIENT_SECRET") or "").strip().strip("'").strip('"'),
    "SCOPES": (os.getenv("SGCONNECT_SCOPES") or "").strip().strip("'").strip('"'),
}

INTERNET_EXPOSED_SOURCE_FIELDS = [
    "server_hostname",
    "server_name",
    "server_friendly_name",
    "server_os_name",
    "server_cloud_type",
    "server_model",
    "application_dali_dsi",
    "server_status",
    "application_irt_code",
    "application_trigram",
    "application_name",
    "server_silo",
    "server_typology",
    "server_uid",
    "server_environment",
    "server_dali_environment",
    "application_managed_by",
    "application_management_rc",
    "application_business_application_manager",
    "application_development_manager",
    "application_business_analyst",
    "application_owned_by",
    "server_dali_qualys_agent",
    "server_dali_qualys_agent_status",
    "server_dali_qualys_last_vuln_scanned_date",
    "server_dali_qualys_agent_last_checked_in",
    "server_owner_account_name",
    "server_dali_internal_creation_date",
    "server_external_creation_date",
    "server_sg_landing_zone",
    "server_cloud_service_provider",
    "server_service_offer",
    "server_tags",
    "ip_address",
    "server_redcat_product",
    "server_edr_onboarding_status",
    "server_edr_health_status",
    "server_edr_av_mode",
    "server_exposed",
    "application_uid",
    "server_team_in_charge",
    "server_team_responsible",
    "server_region",
    "server_country",
    "application_internet_exposition_masai",
]

QUERY_CONFIG = {
    "dali_servers": {
        "index": "dali_servers",
        "search_fields": [
            "server_hostname",
            "server_usual_name",
            "server_friendly_name",
        ],
        "source_fields": [
            "application_name",
            "application_short_label",
            "application_dali_dsi",
            "server_main_application",
            "application_dali_environment",
            "server_environment",
            "server_hostname",
            "application_dali_status",
            "server_status",
            "server_main_ip_address",
            "ip_address",
            "server_usual_name",
            "server_friendly_name",
            "server_cloud_type",
            "server_os_name",
            "total_hosts",
            "hosts_not_in_pce",
            "protected_hosts",
            "not_protected_hosts",
        ],
    },
    "inventory": {
        "index": "inventory",
        "search_fields": ["hostid", "srn"],
        "source_fields": ["hostid", "srn", "ocs_name", "hostname", "beneficiary", "owner_app_name", "status", "ip", "service_name"],
        "beneficiary_search_field": "beneficiary",
        "term_filters": {"status.keyword": ["ACTIVE", "Active", "active", "<UNKNOWN STATUS>", "<unknown status>", "<Unknown Status>", "UNKNOWN", "Unknown", "unknown"]},
    },
    "marley_original": {
        "index": "marley_original",
        "search_field": "hostname",
        "source_fields": [
            "hostname",
            "app_info",
            "app_info.kear_library",
            "uuid",
            "net_info",
            "os_name",
            "os_version",
            "typologie",
            "silos",
            "dns",
            "status",
            "usage",
        ],
        "term_filters": {"status.keyword": ["ACTIVE", "Active", "active", "<UNKNOWN STATUS>", "<unknown status>", "<Unknown Status>", "UNKNOWN", "Unknown", "unknown"]},
    },
    "platform_accounts": {
        "index": "platform_accounts",
        "search_field": "name",
        "source_fields": ["name", "tags"],
    },
    "internet_exposed": {
        "index": "dali_servers",
        "source_fields": INTERNET_EXPOSED_SOURCE_FIELDS,
        "usage_field": "server_usage.keyword",
        "usage_values": ["In Use", "In use"],
        "dali_exposed_field": "server_exposed.keyword",
        "dali_exposed_values": ["Yes", "yes"],
        "masai_exposed_field": "application_internet_exposition_masai.keyword",
        "masai_exposed_wildcard": "*internet*",
    },
    "scroll_timeout": "10m",
    "batch_size": 500,
}
